trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.8
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**surefire-reports/TEST-*.xml'
      goals: 'package'
  - task: Docker@2
    displayName: Build and push an image
    inputs:
      containerRegistry: 'capstoneproject'
      repository: 'joebyrd32/capstone-project'
      command: buildAndPush
      Dockerfile: '$(Build.SourceDirectory)/Dockerfile'
      tags: 'latest'